# Generated by Django 3.2.15 on 2023-08-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='family_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phonenumber',
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('lastname', 'firstname', 'phonenumber', 'adress')},
        ),
    ]
