# Generated by Django 3.2.15 on 2023-08-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('lastname', 'firstname', 'phonenumber', 'address')},
        ),
    ]
