# Generated by Django 3.2.15 on 2023-08-07 15:27

import django.core.validators
from django.db import migrations, models


def tranfser_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items = OrderItem.objects.all()
    if order_items.exists():
        for order_item in order_items.iterator():
            order_item.price = order_item.product.price
            order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20230807_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.RunPython(tranfser_prices),
    ]
