# Generated by Django 3.2.15 on 2023-08-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Готовится', 'Готовитя'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен')], default='new', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
