# Generated by Django 3.2.15 on 2023-08-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230809_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='way_of_payment',
            field=models.CharField(choices=[('Раличными', 'Раличными'), ('Картой', 'Картой')], default='Картой', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
