# Generated by Django 3.2.15 on 2023-08-09 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_way_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='way_of_payment',
            field=models.CharField(choices=[('Наличными', 'Наличными'), ('Картой', 'Картой')], default='Картой', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
