# Generated by Django 3.2.15 on 2023-08-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20230820_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='way_of_payment',
            new_name='payment_method',
        ),
    ]
